spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092 # Kafka Broker Address
    consumer:
      properties:
        schema.registry.url: http://localhost:8081 # Schema Registry Address
        specific.avro.reader: true
        allow.auto.create.topics: false
      group-id: my-group # Consumer Group ID
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: my-topic # Default Kafka Topic Setting

server:
  port: 8082