spring:
  kafka:
    bootstrap-servers: 192.168.55.139:19092,192.168.55.139:29092,192.168.55.139:39092 # Kafka Broker Address
    consumer:
      group-id: data_consumer # Consumer Group ID
      auto-offset-reset: earliest
    template:
      default-topic: my-topic # Default Kafka Topic Setting
    properties:
      schema.registry.url: http://registry.coded-by.me # Schema Registry Address
      specific.avro.reader: true
      allow.auto.create.topics: false
server:
  port: 8083