spring:
  kafka:
    bootstrap-servers: localhost:9092 # Kafka ?? ??
    consumer:
      group-id: my-group # Consumer ?? ID
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: my-topic # ?? Kafka ?? ??

server:
  port: 8082