spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092  # Kafka Broker Address
    producer:
      properties:
        schema.registry.url: http://localhost:8081 # Schema Registry Address
        specific.avro.reader: true
        allow.auto.create.topics: false
    template:
      default-topic: my-topic

server:
  port: 8082