spring:
  kafka:
    bootstrap-servers: 192.168.55.139:19092,192.168.55.139:29092,192.168.55.139:39092  # Kafka Broker Address
    producer:
      properties:
        schema.registry.url: http://registry.coded-by.me # Schema Registry Address
        specific.avro.reader: true
        allow.auto.create.topics: false
    template:
      default-topic: my-topic

server:
  port: 8082