spring:
  kafka:
    bootstrap-servers: localhost:9094  # Kafka ??? ??
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: my-topic  # ?? Kafka ?? ??

server:
  port: 8081